import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
import { GlossaireSearch } from '@/components/sections/GlossaireSearch'
import { GradTag } from '@/components/ui/GradTag'
import { GradText } from '@/components/ui/GradText'
import { SectionReveal } from '@/components/ui/SectionReveal'
import { HeroBg } from '@/components/ui/HeroBg'
import { LiquidMetalButton } from '@/components/canvas/LiquidMetalButton'
import { SchemaOrg } from '@/components/seo/SchemaOrg'
import { buildFAQPage, buildBreadcrumbList } from '@/lib/schema'
import type { Term } from '@/app/glossaire/_types'

const CTAFinal = dynamic(() => import('@/components/sections/CTAFinal').then(m => m.CTAFinal))
const LetterSection = dynamic(() => import('@/app/glossaire/_components/LetterSection').then(m => m.LetterSection))

export const metadata: Metadata = {
  title: 'Digital and AI Glossary · Definitions for SMEs · DKDP',
  description:
    'A complete lexicon of web, SEO and artificial intelligence. Key terms explained simply for SMEs in Switzerland.',
  alternates: {
    canonical: 'https://dkdp.ch/en/glossary',
    languages: {
      'fr-CH': 'https://dkdp.ch/glossaire',
      en: 'https://dkdp.ch/en/glossary',
      'x-default': 'https://dkdp.ch/glossaire',
    },
  },
  openGraph: {
    title: 'Digital and AI Glossary · Definitions for SMEs · DKDP',
    description: "A complete lexicon of web, SEO and artificial intelligence. Key terms explained for SMEs in Switzerland.",
    url: 'https://dkdp.ch/en/glossary',
    locale: 'en_US',
    alternateLocale: ['fr_CH'],
    images: [{ url: '/images/og/glossaire.png', width: 1376, height: 768, alt: 'DKDP glossary: AI and digital lexicon, key terms explained for Swiss SMEs' }],
  },
  twitter: { card: 'summary_large_image', images: ['/images/og/glossaire.png'] },
}

// ---------------------------------------------------------------------------
// Data (English)
// ---------------------------------------------------------------------------

const TERMS: Term[] = [
  {
    term: 'AI Agent',
    category: 'IA',
    definition:
      'An autonomous program that chains actions without human intervention: reading an email, extracting data, updating a CRM and sending a confirmation. Differs from a chatbot in its ability to make decisions across several steps. Cuts repetitive administrative tasks by 25 to 45%.',
    link: '/en/artificial-intelligence/ai-agents',
  },
  {
    term: 'API',
    category: 'Web',
    definition:
      'An interface that lets two pieces of software communicate. Your CRM can automatically send data to your invoicing tool or your newsletter. The foundation of any integration between digital tools.',
  },
  {
    term: 'AEO',
    category: 'SEO',
    definition:
      'Answer Engine Optimization. A discipline aimed at appearing in answers generated by AI (ChatGPT, Perplexity, Google AI Overviews) rather than in the classic blue links. Combines structured content, Schema.org and FAQs so the AI cites your site as a source.',
  },
  {
    term: 'Automation',
    category: 'IA',
    definition:
      'Replacing manual tasks with scripts or AI agents: automatic follow-ups, email sorting, CRM updates. Common tools: Make, Zapier, n8n. A 15-person SME can save several hundred hours a year.',
    link: '/en/artificial-intelligence',
  },
  {
    term: 'Backlink',
    category: 'SEO',
    definition:
      'An inbound link from another site to yours. The more trustworthy the referring sites, the higher your domain authority in Google’s eyes, which directly improves your ranking in search results.',
  },
  {
    term: 'Bounce rate',
    category: 'Web',
    definition:
      'The percentage of visitors who leave a site without interacting. A high rate often signals a problem with relevance, load time or insufficient user experience.',
  },
  {
    term: 'CMS',
    category: 'Web',
    definition:
      'Content Management System. Software that lets you manage and update a site without coding. The most common: WordPress, Sanity, Strapi. Suited to non-technical teams that need autonomy over content.',
  },
  {
    term: 'CRM',
    category: 'General',
    definition:
      'Customer Relationship Management. Software that centralises contacts, sales and customer history. E.g. HubSpot, Salesforce, Pipedrive. Essential for tracking leads and managing the commercial relationship day to day.',
  },
  {
    term: 'CTR',
    category: 'SEO',
    definition:
      'Click-Through Rate. The ratio between impressions and clicks on a link in Google. A good CTR (3 to 5%) signals an attractive title and meta description that encourage users to visit the page.',
  },
  {
    term: 'Claude',
    category: 'IA',
    definition:
      'A language model developed by Anthropic, a competitor to ChatGPT and Gemini. Known for its accuracy, its ability to follow complex instructions and its reliability on sensitive professional tasks.',
  },
  {
    term: 'Conversion',
    category: 'Web',
    definition:
      'A desired action completed by a visitor: getting in touch, buying, signing up. The conversion rate measures how effectively a page turns a visitor into a prospect or active client.',
  },
  {
    term: 'Core Web Vitals',
    category: 'SEO',
    definition:
      'Google metrics assessing user experience: LCP (display speed), INP (interactivity) and CLS (visual stability). These indicators directly influence a site’s ranking in search results.',
  },
  {
    term: 'Crawl',
    category: 'SEO',
    definition:
      'The automatic exploration of a site by Google’s bots to discover and index its pages. A clear structure and an up-to-date sitemap make crawling easier and improve index coverage.',
  },
  {
    term: 'DA',
    category: 'SEO',
    definition:
      'Domain Authority. A score from 0 to 100 (Moz) estimating a domain’s ability to rank on Google, based mainly on the quality and quantity of backlinks the site receives.',
  },
  {
    term: 'DNS',
    category: 'Web',
    definition:
      'Domain Name System. The system that translates a domain name (dkdp.ch) into an IP address readable by servers. A well-configured DNS guarantees availability, security and fast site resolution.',
  },
  {
    term: 'E-E-A-T',
    category: 'SEO',
    definition:
      'Experience, Expertise, Authoritativeness, Trustworthiness. Google’s framework for assessing the reliability of content. In practice: author biographies, verifiable client reviews, a physical address and certifications shown on the site.',
  },
  {
    term: 'ERP',
    category: 'General',
    definition:
      'Enterprise Resource Planning. Integrated management software covering accounting, inventory, HR and production. E.g. SAP, Odoo. Centralises all company data in a single, coherent system.',
  },
  {
    term: 'Fine-tuning',
    category: 'IA',
    definition:
      'Additional training of an AI model on data specific to your industry or company. Improves the model’s accuracy on your specific tasks compared with a general-purpose LLM used without adaptation.',
  },
  {
    term: 'GDPR',
    category: 'General',
    definition:
      'General Data Protection Regulation. The European regulation governing the collection and processing of personal data. It applies to any company processing data of European residents.',
  },
  {
    term: 'GEO',
    category: 'SEO',
    definition:
      'Generative Engine Optimization. A strategy to be cited as a source by generative AI (ChatGPT, Perplexity, Google AI Overviews). Requires content structured into citable passages, sourced statistics and author authority (E-E-A-T).',
  },
  {
    term: 'Generative AI',
    category: 'IA',
    definition:
      'A branch of AI that creates original content: text, images, code, audio. Leading models in 2026: ChatGPT, Claude, Gemini, Midjourney. A trained employee can cut writing time by up to 60%.',
    link: '/en/artificial-intelligence',
  },
  {
    term: 'GPT',
    category: 'IA',
    definition:
      'Generative Pre-trained Transformer. A neural network architecture developed by OpenAI, behind ChatGPT and many modern language models used in business.',
  },
  {
    term: 'Hallucination',
    category: 'IA',
    definition:
      'A phenomenon where an LLM confidently generates false information: fictitious statistics, non-existent citations. Frequency: 3 to 15% depending on the topic. Mitigated with RAG, human review or a limited answer scope.',
  },
  {
    term: 'Hosting',
    category: 'Web',
    definition:
      'A service that makes a site accessible on the internet by storing its files on a server. E.g. Vercel, Infomaniak, OVH. The choice of hosting affects speed, security and, indirectly, SEO.',
  },
  {
    term: 'FADP',
    category: 'General',
    definition:
      'Federal Act on Data Protection. The Swiss equivalent of the European GDPR, in force since September 2023. It regulates the collection, processing and storage of personal data in Switzerland.',
  },
  {
    term: 'Indexing',
    category: 'SEO',
    definition:
      'The process by which Google records a page in its database after crawling it. Without indexing, a page is completely invisible in search results, regardless of its content and quality.',
  },
  {
    term: 'KPI',
    category: 'General',
    definition:
      'Key Performance Indicator. A metric used to measure progress toward an objective. E.g. conversion rate, number of leads, cost per acquisition. A central tool for digital management.',
  },
  {
    term: 'Keyword',
    category: 'SEO',
    definition:
      'A term or phrase typed by a user into a search engine. Choosing and targeting the right keywords is the foundation of any effective SEO strategy.',
  },
  {
    term: 'Landing page',
    category: 'Web',
    definition:
      'A page designed to convert a visitor around a specific offer. Structured to limit distractions and maximise action: a form, a booking or a contact request.',
  },
  {
    term: 'LCP',
    category: 'SEO',
    definition:
      'Largest Contentful Paint. The display time of the largest visible element (image or text). A Google Core Web Vital: an LCP under 2.5 seconds is considered good for user experience.',
  },
  {
    term: 'LLM',
    category: 'IA',
    definition:
      'Large Language Model. A model trained on billions of texts, able to summarise, translate, write and analyse. E.g. Claude, GPT-4o, Gemini. Multiplies team productivity on text-based tasks.',
  },
  {
    term: 'Long-tail keyword',
    category: 'SEO',
    definition:
      'A specific, low-competition search phrase. E.g. "Excel training accounting firm Geneva". Generates less traffic but more qualified visitors who are more ready to convert.',
  },
  {
    term: 'Meta description',
    category: 'SEO',
    definition:
      'The short description shown under the title in Google results. It does not directly affect ranking, but a clear and compelling wording improves the click-through rate (CTR) to the page.',
  },
  {
    term: 'No-code',
    category: 'General',
    definition:
      'Development without writing code, using visual tools: Make, Zapier, Bubble, Webflow. Lets non-developers create automations, forms and simple interfaces on their own.',
  },
  {
    term: 'On-page SEO',
    category: 'SEO',
    definition:
      'Optimisation of elements directly on the page: title and Hn tags, internal linking, load speed, content structure and the presence of target keywords in strategic areas.',
  },
  {
    term: 'Organic traffic',
    category: 'SEO',
    definition:
      'Visits generated by the natural, unpaid results of a search engine. Unlike paid traffic (SEA), it does not stop when an advertising budget is cut.',
  },
  {
    term: 'Prompt',
    category: 'IA',
    definition:
      'A text instruction sent to an LLM. A good prompt specifies the context, the expected format and the constraints. Prompt engineering is a key skill: it significantly improves the quality and accuracy of the answers obtained.',
  },
  {
    term: 'PWA',
    category: 'Web',
    definition:
      'Progressive Web App. A web app installable on a smartphone home screen, working like a native app. Offers a fast experience, available offline, without going through an app store.',
  },
  {
    term: 'RAG',
    category: 'IA',
    definition:
      'Retrieval-Augmented Generation. A technique that connects an LLM to an external database for up-to-date, verifiable answers. Lets your staff query your internal documents through a chatbot. Reduces hallucinations by 30 to 50%.',
  },
  {
    term: 'Redirect 301',
    category: 'SEO',
    definition:
      'A permanent redirect from one URL to another. Transfers the SEO authority of the old page to the new one. Essential during a site redesign or a change of URL structure.',
  },
  {
    term: 'ROI',
    category: 'General',
    definition:
      'Return on Investment. Measures the profitability of an action relative to its cost. Formula: (gain - cost) / cost x 100. A key indicator for deciding on digital and marketing spending.',
  },
  {
    term: 'Schema.org',
    category: 'SEO',
    definition:
      'A structured-markup vocabulary that helps search engines and AI better understand a page’s content. Improves display in the SERP: rich snippets, FAQs, rating stars.',
  },
  {
    term: 'SEA',
    category: 'SEO',
    definition:
      'Search Engine Advertising. Advertising in search engines (Google Ads, Bing Ads). Generates immediate but paid traffic, unlike SEO which produces durable organic results with no cost per click.',
  },
  {
    term: 'SEO',
    category: 'SEO',
    definition:
      'Search Engine Optimization. A set of techniques aimed at improving a site’s organic visibility in Google. Covers content, technical aspects, backlinks and user experience.',
  },
  {
    term: 'SERP',
    category: 'SEO',
    definition:
      'Search Engine Results Page. The results page of a search engine. The top 3 results capture around 54% of total organic clicks. Position 1 remains the priority SEO goal.',
  },
  {
    term: 'SSL/TLS',
    category: 'Web',
    definition:
      'A protocol securing the exchanges between browser and server (the HTTPS padlock). Mandatory: without SSL, Google shows a security warning and penalises the site’s ranking in results.',
  },
  {
    term: 'Token',
    category: 'IA',
    definition:
      'A processing unit for an LLM, equal to about 3/4 of a word in English. LLMs charge per token consumed. A 300-word email represents roughly 400 input tokens.',
  },
  {
    term: 'UI',
    category: 'Web',
    definition:
      'User Interface. All the visual elements the user interacts with: buttons, menus, forms. A good UI makes the journey clear, intuitive and pleasant to use.',
  },
  {
    term: 'URL',
    category: 'Web',
    definition:
      'Uniform Resource Locator. The unique address of a web page. A short, descriptive and well-structured URL improves SEO and helps users understand the content before they even click.',
  },
  {
    term: 'UX',
    category: 'Web',
    definition:
      'User Experience. The overall quality of interaction with a site or product: smoothness, navigation logic, accessibility. A good UX reduces bounce rate and increases conversions.',
  },
  {
    term: 'Vercel',
    category: 'Web',
    definition:
      'A deployment and hosting platform optimised for Next.js. Automatic deployment on every GitHub commit, a global CDN and built-in analytics. Used by DKDP for all its client projects.',
  },
  {
    term: 'Webhook',
    category: 'General',
    definition:
      'A mechanism that automatically sends data from one application to another in real time when an event occurs. E.g. notifying Slack on every new Stripe payment or lead entering the CRM.',
  },
  {
    term: 'WordPress',
    category: 'Web',
    definition:
      'An open-source CMS representing around 43% of the world’s websites. Very flexible thanks to its plugins, but it requires regular maintenance to ensure security and performance.',
  },
  {
    term: 'Workflow',
    category: 'General',
    definition:
      'A sequence of organised steps to accomplish a business process. It can be automated with no-code tools (Make, Zapier) or AI agents, reducing errors and processing time.',
    link: '/en/artificial-intelligence',
  },
]

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function getFirstLetter(term: string): string {
  return term[0].toUpperCase()
}

function groupByLetter(terms: Term[]): Map<string, Term[]> {
  const sorted = [...terms].sort((a, b) => a.term.localeCompare(b.term, 'en'))
  const map = new Map<string, Term[]>()
  for (const t of sorted) {
    const letter = getFirstLetter(t.term)
    if (!map.has(letter)) map.set(letter, [])
    map.get(letter)!.push(t)
  }
  return map
}

const ALL_LETTERS = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']

const FAQ_TERMS = TERMS.slice(0, 18)
const faqItems = FAQ_TERMS.map((t) => ({
  question: `What is ${t.term}?`,
  answer: t.definition,
}))

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default function GlossaryPageEN() {
  const grouped = groupByLetter(TERMS)
  const presentLetters = new Set(grouped.keys())

  return (
    <>
      <SchemaOrg schema={buildFAQPage(faqItems)} />
      <SchemaOrg
        schema={buildBreadcrumbList([
          { name: 'Home', url: 'https://dkdp.ch/en' },
          { name: 'Glossary', url: 'https://dkdp.ch/en/glossary' },
        ])}
      />

      {/* HERO */}
      <HeroBg
        blob1="rgba(124,58,237,0.10)"
        blob2="rgba(212,212,216,0.07)"
        className="min-h-[520px] flex items-center justify-center py-24 px-4"
      >
        <div className="max-w-3xl mx-auto text-center flex flex-col items-center gap-6">
          <SectionReveal>
            <GradTag className="mb-2">Glossary</GradTag>
          </SectionReveal>

          <SectionReveal delay={0.08}>
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-text leading-tight">
              The lexicon of{' '}
              <GradText as="span" className="grad-text">
                digital and AI.
              </GradText>
            </h1>
          </SectionReveal>

          <SectionReveal delay={0.14}>
            <p className="text-text-secondary text-lg max-w-xl">
              All the key web, SEO and artificial intelligence definitions, explained simply for Swiss SMEs.
            </p>
          </SectionReveal>

          <SectionReveal delay={0.18}>
            <p className="text-sm font-medium text-text-secondary">
              {TERMS.length} terms · 5 categories · Updated in 2026
            </p>
          </SectionReveal>
        </div>
      </HeroBg>

      {/* STICKY SEARCH + ALPHABETIC NAV */}
      <div
        className="sticky top-[66px] z-40 w-full border-b border-border"
        style={{
          background: 'color-mix(in srgb, var(--bg) 85%, transparent)',
          backdropFilter: 'blur(24px)',
          WebkitBackdropFilter: 'blur(24px)',
        }}
      >
        <div className="max-w-[1200px] mx-auto px-4">
          {/* Desktop */}
          <div className="hidden md:flex items-center gap-3 py-2">
            <div className="w-56 flex-shrink-0">
              <GlossaireSearch lang="en" terms={TERMS.map(t => ({ term: t.term, category: t.category }))} />
            </div>
            <div className="h-5 w-px flex-shrink-0" style={{ background: 'var(--border-strong)' }} />
            <nav aria-label="Alphabetic navigation" className="flex flex-wrap gap-1 items-center">
              {ALL_LETTERS.map((letter) => {
                const isPresent = presentLetters.has(letter)
                return isPresent ? (
                  <a
                    key={letter}
                    href={`#lettre-${letter}`}
                    className="flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold text-text transition-colors duration-150"
                    style={{ background: 'rgba(167,139,250,0.10)', border: '1px solid rgba(167,139,250,0.25)' }}
                    aria-label={`Go to letter ${letter}`}
                  >
                    {letter}
                  </a>
                ) : (
                  <span
                    key={letter}
                    className="flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold text-text-muted cursor-default select-none"
                    style={{ background: 'var(--surface-subtle)', border: '1px solid var(--border)' }}
                    aria-hidden="true"
                  >
                    {letter}
                  </span>
                )
              })}
            </nav>
          </div>

          {/* Mobile */}
          <div className="md:hidden flex flex-col gap-2 py-2">
            <GlossaireSearch lang="en" terms={TERMS.map(t => ({ term: t.term, category: t.category }))} />
            <nav aria-label="Alphabetic navigation" className="flex flex-wrap gap-1 items-center justify-center pb-1">
              {ALL_LETTERS.map((letter) => {
                const isPresent = presentLetters.has(letter)
                return isPresent ? (
                  <a
                    key={letter}
                    href={`#lettre-${letter}`}
                    className="flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold text-text transition-colors duration-150"
                    style={{ background: 'rgba(167,139,250,0.10)', border: '1px solid rgba(167,139,250,0.25)' }}
                    aria-label={`Go to letter ${letter}`}
                  >
                    {letter}
                  </a>
                ) : (
                  <span
                    key={letter}
                    className="flex items-center justify-center w-7 h-7 rounded-md text-xs font-bold text-text-muted cursor-default select-none"
                    style={{ background: 'var(--surface-subtle)', border: '1px solid var(--border)' }}
                    aria-hidden="true"
                  >
                    {letter}
                  </span>
                )
              })}
            </nav>
          </div>
        </div>
      </div>

      {/* GLOSSARY BODY */}
      <main className="max-w-[1200px] mx-auto px-4 py-16 flex flex-col gap-16">
        {Array.from(grouped.entries()).map(([letter, terms]) => (
          <LetterSection key={letter} letter={letter} terms={terms} lang="en" />
        ))}
      </main>

      {/* INTERMEDIATE CTA */}
      <section className="py-20 px-4">
        <SectionReveal>
          <div
            className="max-w-2xl mx-auto rounded-[20px] p-10 text-center flex flex-col items-center gap-6"
            style={{ background: 'rgba(124,58,237,0.08)', border: '1px solid rgba(124,58,237,0.20)' }}
          >
            <GradTag>Free audit</GradTag>
            <h2 className="text-3xl sm:text-4xl font-black text-text leading-tight">
              Is your website{' '}
              <GradText as="span" className="grad-text--ia">
                optimised for 2026?
              </GradText>
            </h2>
            <p className="text-text-secondary max-w-md">
              Knowing the vocabulary is good. Putting it into practice for your SME is better. Book a free 30-minute audit with DKDP.
            </p>
            <LiquidMetalButton calLink="david-khazaei/planifier-un-appel">
              Book my free audit
            </LiquidMetalButton>
          </div>
        </SectionReveal>
      </section>

      {/* FINAL CTA */}
      <CTAFinal lang="en" />
    </>
  )
}
